name: py3.11-test
channels:
  - defaults
  - pypi
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.2.2
  - pandas=2.2.3
  - polars=1.22.0
  - pyarrow=20.0.0
  - scipy=1.15.1
  - statsmodels=0.14.4
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - tqdm=4.65.0
  - ipywidgets=8.1.5
  - gitpython=3.1.43
  - jupyter=1.1.1
  - notebook=7.3.2
  - pathos=0.2.3
  - pip=25.0
  - pip:
    - ipykernel==6.29.5
    - cartopy==0.24.1